google/python-fire

.travis.yml
fire/completion.py
fire/core.py
fire/fire_test.py
fire/helputils.py
fire/inspectutils.py
fire/inspectutils_test.py
fire/test_components.py
fire/test_components_py3.py

Fix keyword-only arguments

---

fire/helputils_test.py
fire/inspectutils_test.py

Some of the tests are currently failing on windows because the file paths are hardcoded for unix systems. For example, one test is checking for the presence of the below string:
`fire/test_components.py`
The problem is on the windows the actual string that appears is:
`fire\test_components.py`
This is a solved problem, [`os.path.join`](https://docs.python.org/2/library/os.path.html#os.path.join) is smart enough to figure out how to correctly join the files for whatever system the code is being executed on. The tests should now pass on both Windows and Unix systems.

Fix failing tests on Windows due to hardcoded file paths

---

fire/core.py
fire/core_test.py
fire/fire_import_test.py
fire/fire_test.py
fire/test_components.py
fire/testutils.py

@dbieber 
1. Update documentation slightly (I also changed `__init__` name to be `code` because that matches the actual property name on SystemExit)
2. Get all tests to pass and note some additional edge cases (specifically, I'm suggesting we differentiate exit codes from FireError (`2`) from exit codes from user exceptions (`1`))
3. add helper method to capture all stdout and make it easier to write regexps for comparison (i.e. check that we show "the proper..." message on bad use of help)
4. on proper `-- --help` do the same thing as argparse and exit 0
For 4:
```
try:
argparse.ArgumentParser().parse_args()
except BaseException as exc:
print type(exc), exc
raise
›› python example.py blah; echo "Exit status $?"
usage: example.py [-h]
example.py: error: unrecognized arguments: blah …
```

FireExit: ape argparse, flesh out test cases and get everything to pass

---

fire/__init__.py
fire/core.py
fire/core_test.py
fire/fire_import_test.py
fire/fire_test.py
fire/inspectutils_test.py
fire/test_components.py
fire/testutils.py

Exit with a status code if Fire encounters an error
Introduces the "FireExit" exception, a subclass of SystemExit.

Exit with a status code if Fire encounters an error

---

doc/guide.md

```python
fire.Fire(lambda obj: type(x).__name__) 
```
was causing a name error, changed `x` to `obj`

Fix NameError: name 'x' is not defined in Argument Parsing example

---

fire/core.py
fire/core_test.py
fire/test_components.py
fire/testutils.py

Previously, outputs that generated dicts with all hidden keys would error with:
```
Traceback (most recent call last):
File "/Users/jtratner/python-fire/fire/core_test.py", line 100, in testPrintEmptyDict
core.Fire(tc.EmptyDictOutput, 'nothing_printable')
File "/Users/jtratner/python-fire/fire/core.py", line 147, in Fire
_PrintResult(component_trace, verbose=component_trace.verbose)
File "/Users/jtratner/python-fire/fire/core.py", line 198, in _PrintResult
print(_DictAsString(result, verbose))
File "/Users/jtratner/python-fire/fire/core.py", line 221, in _DictAsString
len(str(key)) for key in result.keys()
ValueError: max() arg is an empty sequence
```
This PR fixes that issue by filtering earlier in `_PrintResult` and adds a test case to cover the edge.
(I think I caught all the 2-spaces …

BUG: fix output printing on dict with no printable keys

---

README.md

IPython imports pdb which then imports the troublesome filenames. If these names exists on the pythonpath in front of the builtin modules of the same name, the wrong module is imported.
This commit resolves #19 with documentation

Add troubleshooting section to Guide

---

doc/guide.md
setup.py

As @jtratner notes, I'm not sure about the best way to address the travis CI issues.
But I just ran into that while fixing the broken links in guide.md.

ipython<6.0 for #57; fix broken links in guide.md

---

.travis.yml
fire/core.py
fire/helputils_test.py
fire/inspectutils.py
fire/interact_test.py
setup.py

If IPython isn't available, fall back on _InfoBackup for object details and fall back on the code module for the Python REPL in interactive mode.

Make ipython fully optional

---

fire/parser.py
fire/parser_test.py

Fixes #95
Don't evaluate top level ast.BinOp arguments, treat them as strings instead.

Fix for BinOp in args

---

fire/core.py
fire/fire_test.py

Do not treat arguments that start with '--' as string.

---

fire/parser_fuzz_test.py

__unicode()__ was removed from Python 3 because all strs are unicode.
Executing these lines in Python 3 would raise a NameError.
* https://pythonhosted.org/six/#six.u

unicode() --> six.u() for Python 3 compatibility

---

README.md
docs/api.md
docs/guide.md
docs/index.md
docs/using-cli.md
fire/completion.py
fire/completion_test.py
fire/core.py
fire/parser.py

Re: https://github.com/google/python-fire/issues/56
This adds support for completions for the fish shell. It adds an optional argument to the --completions flag to specify a shell to create completions for.
Usage looks like:
`widget -- --completion` or `widget -- --completion bash`
for bash completions or
`widget -- --completion fish`
for fish completions

Fish completion support

---

fire/parser_fuzz_test.py

Change unicode() —> six.text_type() for Python 3

---

docs/guide.md

The example wass slightly broken, and always sets stories=1. Also changed the phew to be after a whole floor instead of every single step.

Fixes bug setting stories in guide.md

---

fire/core.py
fire/fire_test.py
fire/test_components.py

In response to [this issue](https://github.com/google/python-fire/issues/108).  This adds a feature where a shortcut can be used for boolean arguments of functions.  For example the function
`def foo(bar=False):`
can be invoked as `foo -b` to set bar to True.  While developing this, I came across a couple concerns:
- In detecting whether or not arguments matched the pattern of a bool shortcut, I decided that python's regex library was the best way to solve this problem.  Is adding `re` to imports ok?
- If a naming collision occurs (see final assert of `testBoolShortcutParsing`) the program raises a FireError describing the ambiguity.  Is this a proper manner to use this error in?
- Currently, if a shortcut doesn't match any function argument, it is parsed as-is.  Should something else be …

Issue #108: Shortcuts for boolean arguments

---

fire/core.py
fire/core_test.py
fire/inspectutils.py
fire/test_components.py

Hi, this PR makes the fields of namedtuple objects accessible by their name instead of indices as requested in #157. Also, I extended the test suite and made sure that no existing tests broke.
The exact behaviour is explained in the following:
Assuming a `namedtuple_example.py` script:
```python
from collections import namedtuple
import fire
Point = namedtuple('Point', ['x', 'y'])
p = Point(11, y=22)
if __name__ == '__main__':
fire.Fire(p)
```
Before the PR:
```
python namedtuple_example.py 0  # 11
python namedtuple_example.py 1  # 22
python namedtuple_example.py x  # Throws an exception.
```
After the PR:
```
python namedtuple_example.py x  # 11
python namedtuple_example.py y  # 22
python namedtuple_example.py 0  # Throws an exception since p has no '0' field.
```

Make namedtuple fields accessible by their name

---

fire/completion.py
fire/completion_test.py

This PR changes the completion scripts that are generated by running the `--completion` option for the Fire generated commands. The changes are aimed to give more flexibility to the user. 
- The highlight of this PR is the shift from using `start` based completion to `last-command` based completion. 
- In the `start` based completion, the entire string that has been entered into the command prompt so far is used to map the completion suggestions. This creates inflexibility for the user, causing #136.
- In the `last-command` based completion, suggestions are based on the last command/subcommand (non-option arg) entered by the user. This gives flexibility to the user, to be able to use options in any order, thereby fixing #136.
The features added are:
- Ability to use options in any order. …

Completion Enhancements

---

README.md

This useful badge helps developers know what the latest version number is directly.
Without this, we have to go to pypi.org to check the version number.

add pypi version badge in README

---

fire/inspectutils.py

This PR exposes builtin functions from the standard library to fire and fixes #187.
Previously, certain builtin functions from the standard library (e.g. `math.sin`) would raise a TypeError complaining about getting one less required argument than they need. The original diagnosis was that these functions were written in C and did not expose their signature to`inspect.getfullargspec` or `inspect.signature`. However `math.sin` does expose its signature to these inspect functions:
```python
>>> inspect.getfullargspec(math.sin)
FullArgSpec(args=['x'], varargs=None, varkw=None, defaults=None, kwonlyargs=
[], kwonlydefaults=None, annotations={})
```
The problem was that `fire.inspectutils._GetArgSpecInfo` was incorrectly skipping the first argument of these builtins under the assumption that a …

Exposes builtin functions from the standard library

---

docs/guide.md

- `{name: David}` -> `{name:David}` (no space)
- reference to last example should be the third example ?

fix typos in guide

---

fire/core.py
fire/fire_test.py
fire/test_components.py

* Fix #149 
* Use `dir()` instead of `inspect.getmembers()` to get available methods of given object.
* Refer #149 for explanation.

Use "dir()" to get available methods of object

---

fire/helptext.py
fire/helptext_test.py
fire/test_components.py

Fix #315 by changing the _KeywordOnlyArguments filtering condition.
The condition checked for the presence of the flag in the `kwonlydefaults` field of `FullArgSpec` to consider it as required, but that actually proved the opossite.

Fix #315 Change the _KeywordOnlyArguments filtering condition

---

.github/scripts/build.sh
fire/helptext_test.py
fire/test_components.py
fire/test_components_py3.py

#316 adds a test using Python 3 only features; this CL makes that test only run for Python 3 versions.

Move python 3 only component to test_components_py3.py

---

fire/core.py
fire/core_test.py

Fixes #344 (see issue for more details)
This lets you define a function that will take the result from the Fire component and allows the user to alter it before fire looks at it to render it. 
**Why?** Because you want to define a global way of formatting your data for your CLI across a family of functions/classes where it is impractical (and a **major pain**) to wrap them all.
```python
import random
def data():
return [
{
'is_up': random.choice([False, True]), 
'value_A': random.random(), 
'value_B': random.random() + 100,
'id': random.randint(1000, 5000)} 
for i in range(8)
]
import fire
fire.Fire(data)
```
Outputs this:
```
{"is_up": true, "value_A": 0.6004291859538904, "value_B": 100.77910907893889, "id": 474}
{"is_up": false, "value_A": 0.1406617230697117, "value_B": …
```

Add custom formatter for Fire result

---

fire/core.py
fire/core_test.py

* Lint error cleanup following #345
* Makes new serialize= test deterministic

Lint error cleanup following #345

---

.github/workflows/build.yml
fire/helptext.py
fire/helptext_test.py

Fixes #410 
* Shows default values for kwonly arguments in help text
* Adds test verifying that default values are shown for kwonly args

Show default values for kwonly arguments in help text

---

fire/helptext.py
fire/helptext_test.py
fire/test_components.py

Fix #317 Help text short args

---

fire/console/console_attr.py
fire/custom_descriptions.py

There are small typos in:
- fire/console/console_attr.py
- fire/custom_descriptions.py
Fixes:
- Should read `support` rather than `suport`.
- Should read `pertinent` rather than `pertinant`.
- Should read `environment` rather than `envrionment`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

fire/completion.py

This is a bug that should have been fixed long time ago. (#14)
However, it seems that the bug appeared again.
The issue is that completion for Fire(fn) is missing.
Take the following program as an example.
```python
import fire
def hello(name):
return 'Hello {name}!'.format(name=name)
if __name__ == '__main__':
fire.Fire(hello)
```
When we type `example.py` the command should automatically complete `--name`, but the completion script generated by current Fire fails to do so.
The generated script is as follow.
```bash
_complete-examplepy()
{
local cur prev opts lastcommand
COMPREPLY=()
prev="${COMP_WORDS[COMP_CWORD-1]}"
cur="${COMP_WORDS[COMP_CWORD]}"
lastcommand=$(get_lastcommand)
opts=""
GLOBAL_OPTIONS="--name"
case "${lastcommand}" in
esac
COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) ) …
```

Fix completion for Fire(fn)

---

docs/guide.md

I make a change according to #333.
Tested it and everything is correct.
@dbieber could you please review it?
Thank you.

Modify the grouping example to fit the output

---

mkdocs.yml

"pages" has been deprecated in favor of "nav"

Change mkdocs from pages to nav

---

.github/scripts/build.sh
.github/scripts/requirements.txt

I would suggest to frezee CI depencies to limit accidental test failing die to unrelated changes... as I see failing tests in https://github.com/google/python-fire/pull/428#issuecomment-1412539465 without touching anything significant
so these versions are set as of Dec 2022 as that was last :green_circle: commit to the main branch
in the next PR #432 we can add dependabot, which is GitHub build-in mechanism to keep dependencies safely bumped...

freeze CI requirements

---

.github/scripts/build.sh

Follow on from https://github.com/google/python-fire/pull/431 to fix the CI.
Sample build: https://github.com/hugovk/python-fire/actions/runs/4068330039

Fix path to requirements.txt

---

setup.cfg

This can be omitted entirely because setuptools automatically includes `LICENSE`:
> A list of glob patterns for license related files that should be included. If neither license_file nor license_files is specified, this option defaults to `LICEN[CS]E*`, `COPYING*`, `NOTICE*`, and `AUTHORS*`.
https://setuptools.pypa.io/en/latest/references/keywords.html#keywords
```console
$ python setup.py --licence
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py:775: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/config/setupcfg.py:520: …
```

Fix deprecation warning: LICENSE is autodetected

---

.github/workflows/build.yml
setup.py

I believe that Fire is fully compatible with all new Python versions so:
- adding tags to package
- adding testing for them

adding python 3.10 [tag & CI]

---

fire/core.py

#442 was accidentally closed
This is really minor, this PR aims to provide a description of the serialize keyword argument in the corresponding doc-string. In case the wording is not the proper one, feel free to propose a change.

Add missing argument description

---

.github/dependabot.yml

This is a follow-up work of #431 to safely bump versions via PR, also triggering all CI to ensure development stability...

adding GH dependabot

---

fire/parser.py

ast.Str is planned to removed in Python 3.14, use ast.Constant instead whenever the later is available.
This PR resolves #523, if that's an issue. :joy_cat: 
All test cases are passed and the pylint score is not changed.
> Your code has been rated at 9.87/10 (previous run: 9.87/10, +0.00)

Use ast.Constant for recent Python versions

---

fire/completion.py
fire/core.py
fire/core_test.py
fire/custom_descriptions.py
fire/fire_test.py
fire/helptext_test.py
fire/inspectutils.py
fire/inspectutils_test.py
fire/parser_fuzz_test.py
fire/test_components.py
fire/testutils.py
fire/testutils_test.py
fire/value_types.py

This PR includes:
* assuming Python 3 for test skipping
* assuming Python 3 for fire's various type checks
* assuming Python 3 for imports (like asyncio)
* assuming Python 3 for getting function signatures
* six is no longer considered a hidden module (and so if a user of fire has six in their globals when they call Fire(), six will now show up where it used to be hidden)
This PR does not remove six from console/ code.

remove six: Replace six.string_types and six.integer_types, etc.

---

.github/workflows/build.yml

I suggest including testing on Mac and Win. 
also, the addition of OS builds does not need to be so extensive and could be listed in the `include` section adding 3.8 as the oldest and 3.12 as the latest python version

ci: expand build matrix for major OS

---

fire/inspectutils.py

Use Neutral theme for Inspector

---

fire/inspectutils.py
fire/parser.py

Adds "# type: ignore" comments to satisfy ty

Add type hints to satisfy ty
